### ISSUE TITLE
Can't create item without id

### ISSUE THREAD

**Issue by sm1th** [Azure/azure-cosmos-js#241]
In C#, when we have a container which has the `partitionKey` set to the `id` of a document, we can use the SQL API to create a document without specifying an id, and it will generate the id and set the partitionKey.

However, this does not work in JavaScript. Example:
```js
const itemBody = {"foo": "bar"};
const { item } = await client.database(databaseId).container(containerId).items.create(itemBody);
// the above throws: "PartitionKey extracted from document doesn't match the one specified in the header"
```

I would like cosmos to generate the document id. Is there an option I can provide to the request for it to work, or is this not supported at this time?

**Comment by christopheranderson** [comment]
We removed that feature as it created a good deal of confusion in our experience(it's also gone in the latest 3.x.x .NET SDK. It led to behaviors where customers would use queries to do item lookups because they didn't build their application around having the id around. Cosmos has really fast, efficient reads by id+partition key and we want to encourage the practice of using item.read for hotpath operations.

We have a feature planned for later this semester (FYQ3/4) which would allow you to use a plugin to do this, but it's not something we want to support out of the box based on our past experience.

**Comment by sm1th** [comment]
@christopheranderson The response from the `create()` method would have given you the new document with the id, correct? So I'm confused as to why customers were querying when they had the id to use...

So the solution now then is to generate my own uuid to use as an id? IMO that puts an unnecessary burden on the developer.
