### ISSUE TITLE
Get the change feed for all partitions of a collection

### ISSUE THREAD

**Issue by AndyBitz** [Azure/azure-cosmos-js#265]
In order to get the change feed for a partioned collection with `readChangeFeed` you have to specify a `partionKey`.

However, if the partition path is the `ID` of the document, you can only get the change feed of one document.

Is there a way to get the change feed for all partitions of a collection, either with this package or with the REST API?

**Comment by christopheranderson** [comment]
Today, with the Node.js SDK, you can't monitor all partitions at once, but it is a feature we plan on adding soon. 

It is possible to do this via REST API but quite complex because you have to handle the shifting layout of Cosmos DB (increasing number of partitions, partition keys being shifted around, etc.). Would not recommend this approach.

Today, easiest option is to use the Cosmos DB trigger in Azure Functions which does this for Node.js/Java/Python/etc.

**Comment by AndyBitz** [comment]
@christopheranderson Thanks for your answer! I'll be looking forward to this.

I guess the issue can be closed in favour of #268?

**Comment by wpitallo** [comment]
Hi, so you cant get change feed across partitions?  How reliable / what grantee is there that the Cosmos DB trigger will never fail? Cosmos DB seems to really come up short when working with many partitions.

**Comment by wpitallo** [comment]
@christopheranderson when do you expect to have this feature available?

**Comment by christopheranderson** [comment]
Probably before end of June. Currently, we point folks to try using Azure Functions if you need change feed processor functionality with JavaScript.

**Comment by christopheranderson** [comment]
Covered by https://github.com/Azure/azure-sdk-for-js/issues/4808

**Comment by wpitallo** [comment]
@christopheranderson please could you provide a link to the documentation for this?
