### ISSUE TITLE
How to manage document attachments?

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-cosmos-js#365]
I'm using version 2.1.5 of the SDK but unfortunately couldn't find any information there to manage [`document attachments`](https://docs.microsoft.com/en-us/rest/api/cosmos-db/attachments). I was expecting to find some operations related to document attachments in `Item` class but couldn't find anything there.

Has this functionality removed from the SDK or am I missing something?

**Comment by southpolesteve** [comment]
@gmantri You are not missing anything. We don't currently have attachment support in the current major release (v2) or the upcoming v3 release. If you need attachment support in the short term, you will have to use the v1 SDK (https://github.com/Azure/azure-cosmosdb-node) or the REST API.
 
Attachments are one of the features we haven't seen many requests for in JS. In practice, it seems most people are using Azure Blob storage or some other service directly rather than cosmos attachments. I will chat with the team over here and see what it would take to add it.

**Comment by gmantri** [comment]
Thanks @southpolesteve! Do let me know if you want to close this thread now or wait until you had a chance to speak with the team.

**Comment by christopheranderson** [comment]
Attachments are on the road to deprecation. Announcement is coming at the end of the month. We've removed support for them already in the newer libraries.
