### ISSUE TITLE
No option to read change feed for a partition key range

### ISSUE THREAD

**Issue by arulselvam** [Azure/azure-cosmos-js#387]
There is no way to read change feed for a partition key range in the nodejs sdk. Other language SDK has this feature.

**Comment by christopheranderson** [comment]
We've removed partition key range id from all the new SDKs. It leads to a lot of issues due to needing to understand and handle splits. It also prevented a yet announced feature.

In its place, we're planning a similar "token" based experience that will handle splits/etc. automatically under the covers. I've created this issue to track this request: https://github.com/Azure/azure-sdk-for-js/issues/4826
