### ISSUE TITLE
Simplifying return objects for methods with network requests

### ISSUE THREAD

**Issue by southpolesteve** [Azure/azure-cosmos-js#53]
Consider a simple case of reading and updating an item:

``` js
const item = await cosmos.item(id).read()

item.foo = "bar"

await cosmos.items.upsert(item)
```

While this API works for basic operations, it does not expose HTTP headers or any other raw request data. Many advanced uses of cosmos need this data. We currently solve this by returning a wrapper object for all methods with underlying network requests:

``` js
const { body: item, headers }  = await cosmos.item(id).read()

item.foo = "bar"

await cosmos.items.upsert(item)
```

Unfortunately, this complicates the returned object and API for simple usage. Ideally we could support both use cases. Return objects could be simple but also provide metadata that advanced users need. With newer JavaScript features this may be possible. These are some approaches we are considering.

## 1: Use `Symbol`

Cosmos SDK can use a symbol to store data directly on the returned database object.

``` js
// Cosmos SDK Code
cosmos.headers = Symbol('headers')

// User code
const item = await cosmos.item(id).read()
const headers = item[cosmos.headers]
```

[#34](https://github.com/Azure/azure-cosmos-js/issues/34) contains some previous discussion of this approach.

### Pros
- Getting headers looks just like normal object property access
- Symbols as keys allows us to add metadata without conflicting with user data. These keys are omitted when iterated or stringified so users can safely pass them back to cosmos without polluting data.

### Cons
- Requires advanced users to be familiar with `Symbol` which is a relatively new JS language feature
- Requires polyfill in IE

## 2: `getHeaders` method

This is a twist on proposal 1. Symbols are still used as keys, but we expose a utility method so symbols are not exposed to user code.

``` js
// Cosmos SDK Code
const headersKey = Symbol('headers')
comsos.getHeaders = obj => obj[headersKey]

// User code
const item = await cosmos.item(id).read()
const headers = cosmos.getHeaders(item)
```

#### Pros
- Similar to apporach 1 but without exposing users to `Symbol`

#### Cons
- Requires polyfill in IE
- `getHeaders` may look like magic to some users

## 3: Extend `Promise`

This approach returns a special class of promise that would allow users to control the return type.

``` js

// Cosmos SDK code
class CosmosRequestPromise extends Promise {
	includeHeaders() { /* implementation ommited */ }
}

// User code
const item = await cosmos.item(id).read()

const { body: item, headers } = await cosmos.item(id).read().includeHeaders()
```

#### Pros
- Doesn't use Symbol at all

#### Cons
- Requires creating and maintaining our own promise type
- `includeHeaders` may look like magic to some users
- Implementation details are still unclear. This approach seems possible, but we haven't built a POC.

**Comment by bterlson** [comment]
@reconbot I suggested similarly but @southpolesteve pointed out that any name you pick could possibly conflict with a field in the document you stored since it has no limitations on property names (IIUC anyway).

**Comment by TooTallNate** [comment]
1. sounds like the most "modern" JS way of doing it. Given that this module is intended to be used with async/await I think it makes sense to stick to the new features to encourage adoption, etc. Symbols are also [easy to polyfill](https://github.com/medikoo/es6-symbol).

**Comment by christopheranderson** [comment]
1 & 2 are compatible. 2 is effectively just a utility method for getting the right index.

Other advantages of doing 1 & 2 together is supporting some intelligent utility methods. Most folks don't want the headers, they want a specific property from the headers such as RUs or activity id. We could have `client.getRUs` and `client.getActivityId` methods as well, which short cut and abstract away the details for folks.

**Comment by bterlson** [comment]
Putting some emailed thoughts here in case they're useful to people...

Extending Promise (3) is likely not a good idea. Promise subclassing is a bit of a boondoggle in my opinion.

Symbols (1) are really annoying to use and IMO should typically not be used for simple property lookup scenarios (they’re more a plumbing thing, useful for different bits of code to communicate IMO). Methods (2) are better, or (1) and (2) together would be ok, but I worry people will struggle with it being a static method (the difference between `item.getHeaders()` vs `cosmos.getHeaders()`).

If all you care about is that the symbols won’t be part of JSON.stringify, using string names that are non-enumerable can work. You could also implement `toJSON` and exclude known keys. But this may not work well due to the cosmos DB document being able to contain any key.

But there are direct parallels here with the fetch API. It seems suspicious to create another interface for receiving a response optionally with headers.  The “downside” of the fetch API is you have two steps to get the JSON payload: `let resp = await fetch(…); await resp.json()`. But the upshot is you get a lot of added flexibility to handle multiple content types, exposing the response body as a stream rather than just a promise resolution.

You could imagine a higher-level API that gives no access to headers and just returns the body parsed as JSON layered on a fetch-alike underneath that offers more advanced functionality.

**Comment by southpolesteve** [comment]
Thank you everyone for the feedback! We did some user testing and the results were mixed. There was some initial friction in understanding how this worked. Its not really discoverable via intellisense so we'd have to rely entirely on docs.

As a result we have decided to hold off on this change. It is possible we'll pick it up again in the future.
